### ISSUE TITLE
Objects move with video input

### ISSUE THREAD

**Issue by LeifFrederiksen** [awe-media/awe.js#35]
Hi,
I am trying out the examples, to see if this is something I can use in some clever business case.

What I think I need is to have the video stream of the environment facing camera shown, and to then overlay it with objects that are "fixed in space" by some sort of geo-tag. So when I move the device around, it will show me the environment, but only those objects that are located where I point the device.

When I try the examples/basic/ar.html I get the video stream, but the object (the spinning cube) is always shown on my screen no matter where I point the phone.

When I try the examples/basic/vr.html however, no video stream is shown (this is expected), but the objects stay on their places in space, so when I move the phone around, I can look at different objects.

What I need to accomplish is have BOTH the video (from the ar.html example) AND the "objects fixed in space not on screen" effect from the vt.html example.

How can I accomplish this?

Regards
Leif

**Comment by awe-media** [comment]
Hi @LeifFrederiksen sounds like there's an issue with your vr.html file.  Both the ar.html and vr.html file do effectively the same thing except for the background. Or perhaps you could provide some screencasts as it's not completely clear from your language what the problem is here.

BTW: We have another awe.js release coming up soon - but in the meantime you can see how the Locative AR and 360°/VR patterns work by setting up a free trial at https://try.awe.media.

**Comment by ScottBeeson** [comment]
The same thing happens to me.  I'm using the code from /examples/basic/ar.html and it puts a cube in the viewport but it's just static.

http://i.imgur.com/aQPNCyQ.gif
