### ISSUE TITLE
Directions based on load position not Compass Direction

### ISSUE THREAD

**Issue by derricksharp** [awe-media/awe.js#37]
I'm using the basic example that I've loaded on my server:

https://maps.horrocks.com/awe/examples/basic/ar.html

No matter which compass direction I'm facing when the page loads, the page loads facing the white cube (id: south). I've tested it on a Google Pixel and Samsung Galaxy 7. Shouldn't the red block always be on the north of the camera?

Thanks!

**Comment by gpanneti** [comment]
Hello @derricksharp !

This is because Chrome added a new version of the orientation event, called *deviceorientationabsolute*. If *window.ondeviceorientationabsolute is defined*, you should use it instead of the standard deviceorientation event.

I made a little modification in the awe_gyro file to handle it when available but its a little bit too dirty for now to propose a pull request...

**Comment by awe-media** [comment]
Hi @derricksharp - @gpanneti is generally right. There's 'deviceorientation' which is "game based orientation" and there's 'deviceorientationabsolute' which is 'world based". But of course iOS is slightly different too.

You can see this functionality if you setup a free trial at https://awe.media. Here's an intro to adding geo content https://awe.media/support/creating-locative-ar-for-the-web

NOTE: We will be releasing this code as part of a new awe,js update in the near future.

**Comment by derricksharp** [comment]
@awe-media & @gpanneti Thanks for the info. I put together a little function to get it working.
