### ISSUE TITLE
detect marker and remember position

### ISSUE THREAD

**Issue by Fuzzyma** [awe-media/awe.js#39]
Is it possible to detect  a marker on an image, get its pose in 3d and remember this position relative to the camera? So that moving or tilting will transform the detected marker position to the right spot even if the marker itself cant be detected anymore (because out of view, to far away, to near etc...)
 
In my special case I detect aruco markers and calculate their 3d position with posit (I am using js-aruco).
This gives me translation, rotation, tilt... of the marke.
I would like to remember these position so that I can draw something on the marker even if the marker is not detected anymore. See it as a backup until the marker is detected again.
For this I would use the position and acceleration sensors of my android device.

Is this possible with awe.js?

**Comment by awe-media** [comment]
Hi @Fuzzyma yes you can do this - just take the world position/orientation of your poi and create a new one in that same transform. Update/show this when you loose tracking. Then hide it again when you resume tracking. That should give you what you describe above.

If you need any more information on this just shout - otherwise we'll close this issue.
